name: Build and Deploy Go Application

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every night at midnight
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build the Go executable
        run: go build -o myapp .

      - name: Build Docker image
        run: |
          docker build -t bilalis/myapp:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push bilalis/myapp:latest


